import std/[options, setutils, strutils, hashes, tables, strformat]

import translations

type TokenKind* = enum
  tk_none # Will be skipped by `add_token`
  tk_unknown # Will not be skipped by `add_token`, use for e.g. unknown characters
  tk_whitespace
  tk_comment
  tk_text # Generic text, i.e. descriptions
  tk_number
  tk_string
  tk_operator # '+', '-', '/', ...
  tk_separator # ',', ':', ...
  tk_bracket
  tk_keyword
  tk_identifier # Generated by the parsing functions, should normally be replaced
  tk_mnenomic
  tk_literal # false, true, big, little, ...
  tk_type_name # S64, immediate, custom field names
  tk_pattern_name # concat in "pattern concat(a, b)"
  tk_pattern_variable # a, b in "pattern concat(a, b)"
  tk_pattern_variable_ref # a in "{a}"
  tk_field_name # The names defined within custom fields
  tk_field_ref # %a, %some_name
  tk_bit_0 # Bit 0 in the bit pattern
  tk_bit_1 # Bit 1 in the bit pattern
  tk_bit_dont_care # ? in the bit pattern
  tk_label
  tk_const # @0xFF (pad-to directive)
  tk_header # [settings], [fields], [patterns], [instructions]

  # Control instructions
  tk_new_instruction

const CONTROL_TOKENS = {tk_new_instruction}

type Token* = object
  start*: int
  finish*: int
  tk*: TokenKind

type TokenString* = object
  s*: string
  tk*: TokenKind

type StreamSlice* = object
  tokens: ref seq[Token]
  source: ref string
  start: int
  finish: int

type RestorePoint* = object
  s: StreamSlice
  token_count: int
  last_token_finish: int

type ParseError* = object of ValueError
  line*: int

const IDENTIFIER_FIRST =
  setutils.toSet("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_")
const IDENTIFIER_NEXT =
  setutils.toSet("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.")
const QUOTES* = {'"', '\'', '`'}
const WHITESPACES* = {' ', '\t', '\r'}

func new_stream_slice*(source: string, with_tokens = false): StreamSlice =
  var reference = new(string)
  reference[] = source
  result = StreamSlice(source: reference, start: 0, finish: source.len)
  if with_tokens:
    result.tokens = new(seq[Token])

func empty_slice*(s: StreamSlice): StreamSlice =
  result = s
  result.finish = s.start

func finished*(s: StreamSlice): bool =
  assert not isNil(s.source)
  return s.start >= s.finish

func len*(s: StreamSlice): int =
  assert not isNil(s.source)
  return s.finish - s.start

func `$`*(s: StreamSlice): string =
  assert not isNil(s.source)
  return s.source[s.start ..< s.finish]

func `[]`*(s: StreamSlice, index: int): char =
  assert not isNil(s.source)
  if s.start + index < 0 or s.start + index >= s.finish:
    return
  return s.source[s.start + index]

func `[]`*(s: StreamSlice, index: BackwardsIndex): char =
  assert not isNil(s.source)
  let i = s.finish - index.int
  if i < 0:
    return
  return s.source[i]

func `[]`*(s: StreamSlice, index: HSlice): StreamSlice =
  assert not isNil(s.source)
  result = s
  result.start += index.a
  result.finish -= index.b.int - 1

func contains*(s: StreamSlice, c: char): bool =
  assert not isNil(s.source)
  for i in s.start ..< s.finish:
    if s.source[i] == c:
      return true
  false

func get_index*(s: StreamSlice): int =
  assert not isNil(s.source)
  return s.start

func set_index*(s: var StreamSlice, value: int) =
  assert not isNil(s.source)
  s.start = value

func get_slice*(s: StreamSlice, start: int, finish: int): StreamSlice =
  result = s
  result.start = start
  result.finish = finish

func get_string*(s: StreamSlice, start: int, finish: int): string =
  return $s.source[start .. finish - 1]

func dbg*(s: StreamSlice): string =
  return
    s.source[0 .. s.start - 1] & "\u001b[31m" & s.source[s.start .. s.finish - 1] &
    "\u001b[0m" & s.source[s.finish ..^ 1]

func checkpoint*(s: StreamSlice): RestorePoint =
  result.s = s

  if isNil(s.tokens):
    return

  result.token_count = s.tokens[].len
  result.last_token_finish =
    if s.tokens[].len > 0:
      s.tokens[][^1].finish
    else:
      0

func restore*(s: var StreamSlice, cp: RestorePoint) =
  assert s.source == cp.s.source, "RestorePoint does not apply to this stream"
  s = cp.s

  if isNil(s.tokens):
    return

  assert cp.token_count <= s.tokens[].len, "`restore` cannot recreate deleted tokens"
  s.tokens[].set_len(cp.token_count)
  if cp.token_count > 0:
    s.tokens[][^1].finish = cp.last_token_finish

func to_token_string*(s: StreamSlice, t: Token): TokenString =
  TokenString(s: $s.get_slice(t.start, t.finish), tk: t.tk)

func collect_tokens*(s: StreamSlice): seq[Token] =
  if not isNil(s.tokens):
    return s.tokens[]

func collect_token_strings*(s: StreamSlice): seq[TokenString] =
  if not isNil(s.tokens):
    result.set_len(s.tokens[].len)
    for i, t in s.tokens[]:
      result[i] = to_token_string(s, t)

func restore_tokens*(s: var StreamSlice, tokens: seq[Token]) =
  if not isNil(s.tokens):
    s.tokens[] = tokens

func stop_tokenization*(s: var StreamSlice) =
  s.tokens = nil

func add_token*(s: StreamSlice, tk: TokenKind) =
  # Adds a token starting from the end of the last token to the start of s
  if tk == tk_none or isNil(s.tokens):
    return

  let start =
    if s.tokens[].len == 0:
      0
    else:
      s.tokens[][^1].finish

  let finish = s.start.min(s.source[].len)

  if tk in CONTROL_TOKENS:
    assert start == finish
    s.tokens[].add(Token(start: start, finish: finish, tk: tk))
    return

  if start == finish: # Token would be zero length, don't generate it at all
    return
  assert finish > start,
    &"Invalid call to add_token, forgot to restore properly? (start={start}, finish={finish})"
  if s.tokens[].len > 0 and s.tokens[][^1].tk == tk:
    s.tokens[][^1].finish = finish
  else:
    s.tokens[].add(Token(start: start, finish: finish, tk: tk))

func change_token_kind*(s: StreamSlice, expected: TokenKind, new_token: TokenKind) =
  if isNil(s.tokens):
    return

  assert s.tokens[][^1].tk == expected
  s.tokens[][^1].tk = new_token

func peek*(s: StreamSlice): char =
  assert not isNil(s.source)
  if s.start >= s.finish:
    return
  return s.source[s.start]

func peek*(s: StreamSlice, offset: int): char =
  assert not isNil(s.source)
  let i = s.start + offset
  if i >= s.finish:
    return
  return s.source[i]

func skip*(s: var StreamSlice, amount = 1, tk = tk_none) =
  assert not isNil(s.source)
  s.start += amount
  if s.start > s.finish:
    s.start = s.finish
  add_token(s, tk)

func read*(s: var StreamSlice, tk = tk_none): char =
  assert not isNil(s.source)
  if s.start > s.source[].high:
    return
  result = s.source[s.start]
  s.start += 1
  add_token(s, tk)

func take*(s: var StreamSlice, c: char): bool =
  if s.start > s.source[].high:
    return
  result = s.source[s.start] == c
  if result:
    s.start += 1

func matches*(s: var StreamSlice, value: string, increment = true, tk = tk_none): bool =
  for i in 0 .. value.high:
    if peek(s, i) != value[i]:
      return false
  if increment:
    s.start += value.len
    add_token(s, tk)
  return true

func matches*(s: var StreamSlice, value: char, increment = true, tk = tk_none): bool =
  if peek(s) == value:
    if increment:
      s.start += 1
      add_token(s, tk)
    return true

func matches*(
    s: var StreamSlice, value: set[char], increment = true, tk = tk_none
): bool =
  if peek(s) in value:
    if increment:
      s.start += 1
      add_token(s, tk)
    return true

func skip_comment*(
    s: var StreamSlice, line_comments = @[";", "//"], block_comments = @{"/*": "*/"}
): (bool, int) =
  for (start_sym, end_sym) in block_comments:
    if s.matches(start_sym):
      var line_count = 0
      while not finished(s) and not s.matches(end_sym):
        if peek(s) == '\n':
          line_count += 1
        s.start += 1
      add_token(s, tk_comment)
      return (true, line_count)
  for lc in line_comments:
    if s.matches(lc):
      while not finished(s) and peek(s) != '\n':
        s.start += 1
      add_token(s, tk_comment)
      return (true, 0)

func skip_whitespaces*(
    s: var StreamSlice, line_comments = @[";", "//"], block_comments = @{"/*": "*/"}
) =
  while peek(s) in WHITESPACES:
    s.start += 1
  add_token(s, tk_whitespace)
  if skip_comment(s, line_comments, block_comments)[0]:
    skip_whitespaces(s)

func skip_newlines*(
    s: var StreamSlice, line_comments = @[";", "//"], block_comments = @{"/*": "*/"}
): bool {.discardable.} =
  var any_newline = false
  while peek(s) in WHITESPACES + {'\n'}:
    if read(s) == '\n':
      any_newline = true
  add_token(s, tk_whitespace)
  if skip_comment(s, line_comments, block_comments)[0]:
    skip_newlines(s) or any_newline
  else:
    any_newline or finished(s)
      # If we are at the end of the file, act as if we had an infinite stream of newlines

template on_err*[T](inp: (string, T), callback: untyped): T =
  let (raw_err, res) = inp
  if raw_err != "":
    let err {.inject, used.} = raw_err
    callback
  else:
    res

func get_identifier*(s: var StreamSlice, tk = tk_identifier): StreamSlice =
  result = s
  result.finish = s.start

  if peek(s) notin IDENTIFIER_FIRST:
    return

  skip(s)
  result.finish += 1

  while peek(s) in IDENTIFIER_NEXT:
    skip(s)
    result.finish += 1
  add_token(s, tk)

func get_sub_identifier*(s: var StreamSlice, tk = tk_identifier): StreamSlice =
  # Parse an identifier that can start with a number

  result = s
  result.finish = s.start

  while peek(s) in IDENTIFIER_NEXT:
    skip(s)
    result.finish += 1
  add_token(s, tk)

func get_number(
    s: var StreamSlice, base: var int, optional_start_symbols: set[char]
): (string, StreamSlice) =
  result[1] = s
  result[1].finish = s.start

  if peek(s) in optional_start_symbols:
    result[1].finish += 1
    skip(s)

  if peek(s) in {'0', '#'}:
    if peek(s, 1) == 'x':
      const HEX = HexDigits + {'_'}

      skip(s, 2)
      result[1].finish += 2
      while peek(s) in HEX:
        skip(s)
        result[1].finish += 1
      add_token(s, tk_number)
      base = 16
      return result
    if peek(s, 1) == 'o':
      const OCT = Digits - {'8', '9'} + {'_'}

      skip(s, 2)
      result[1].finish += 2
      while peek(s) in OCT:
        skip(s)
        result[1].finish += 1
      add_token(s, tk_number)
      base = 8
      return result
    if peek(s, 1) == 'b':
      const BIN = {'0', '1', '_'}

      skip(s, 2)
      result[1].finish += 2
      while peek(s) in BIN:
        skip(s)
        result[1].finish += 1
      add_token(s, tk_number)
      base = 2
      return result

  const DEC_FIRST = Digits
  const DEC_NEXT = DEC_FIRST + {'_'}

  if peek(s) notin DEC_FIRST:
    return
      (translate(31337_22452670489981, "Expected a number literal"), empty_slice(s))
  skip(s)
  result[1].finish += 1
  while peek(s) in DEC_NEXT:
    skip(s)
    result[1].finish += 1
  add_token(s, tk_number)
  base = 10

func get_signed*(s: var StreamSlice, base: var int): (string, StreamSlice) =
  result = get_number(s, base, {'-', '+'})
  if result[0].len > 0:
    result[0] = translate(31337_73973243772156, "Expected a signed number literal")

func get_signed*(s: var StreamSlice): (string, StreamSlice) =
  var base: int
  return get_signed(s, base)

func get_unsigned*(s: var StreamSlice, base: var int): (string, StreamSlice) =
  result = get_number(s, base, {})
  if result[0].len > 0:
    result[0] = translate(31337_71666516845083, "Expected an unsigned number literal")

func get_unsigned*(s: var StreamSlice): (string, StreamSlice) =
  var base: int
  return get_unsigned(s, base)

func get_hex*(s: var StreamSlice, prefix: string = "0x"): (string, StreamSlice) =
  result[1] = s
  result[1].finish = s.start

  if not matches(s, prefix, increment = false):
    return (
      translate(31337_72110029133381, "Expected {prefix}", ("prefix", prefix)),
      empty_slice(s),
    )

  skip(s, prefix.len)
  result[1].finish += prefix.len
  while peek(s) in HexDigits + {'_'}:
    skip(s)
    result[1].finish += 1
  add_token(s, tk_number)
  return result

func xdigit_to_value*(c: char): int =
  # Assumes that c has already been verified
  if c in DIGITS:
    return c.ord - '0'.ord
  if c in {'A' .. 'Z'}:
    return c.ord - 'A'.ord + 10
  return c.ord - 'a'.ord + 10

func parse_unsigned*(s: StreamSlice): (string, uint64) =
  var start_digits = 0
  if s[0] == '-':
    return (translate(31337_51855228989260, "Invalid unsigned int literal"), 0'u64)

  if s[0] == '+':
    start_digits = 1

  var base = 0'u64
  var digits = {'_'}

  if s.len - start_digits < 3 or s[start_digits + 1] notin {'x', 'o', 'b'}:
    base = 10
    digits = digits + {'0' .. '9'}
  else:
    case s[start_digits + 1]
    of 'x':
      base = 16
      digits = digits + HexDigits
    of 'o':
      base = 8
      digits = digits + {'0' .. '7'}
    else:
      base = 2
      digits = digits + {'0' .. '1'}

    start_digits += 2

  let overflow_threshold_mul = uint64.high div base
  var num = 0'u64
  for i in start_digits ..< s.len:
    if s[i] notin digits:
      return (translate(31337_64926004981217, "Invalid int literal"), 0'u64)

    if s[i] == '_':
      continue

    if num > overflow_threshold_mul:
      return (translate(31337_33551107641907, "Int literal too big"), 0'u64)

    num *= base

    let digit = cast[uint64](xdigit_to_value(s[i]))
    if num > uint64.high - digit:
      return (translate(31337_33551107641907, "Int literal too big"), 0'u64)
    num += digit

  return ("", num)

func parse_signed*(s: StreamSlice): (string, uint64) =
  var is_negative = false
  var start_digits = 0
  if s[0] == '-':
    is_negative = true
    start_digits = 1
  elif s[0] == '+':
    start_digits = 1

  var base = 0'u64
  var digits = {'_'}

  if s.len - start_digits < 3 or s[start_digits + 1] notin {'x', 'o', 'b'}:
    base = 10
    digits = digits + {'0' .. '9'}
  else:
    case s[start_digits + 1]
    of 'x':
      base = 16
      digits = digits + HexDigits
    of 'o':
      base = 8
      digits = digits + {'0' .. '7'}
    else:
      base = 2
      digits = digits + {'0' .. '1'}

    start_digits += 2

  let overflow_threshold_mul = uint64.high div base
  var num = 0'u64
  for i in start_digits ..< s.len:
    if s[i] notin digits:
      return (translate(31337_64926004981217, "Invalid int literal"), 0'u64)

    if s[i] == '_':
      continue

    if num > overflow_threshold_mul:
      return (translate(31337_33551107641907, "Int literal too big"), 0'u64)

    num *= base

    let digit = cast[uint64](xdigit_to_value(s[i]))
    if num > uint64.high - digit:
      return (translate(31337_33551107641907, "Int literal too big"), 0'u64)
    num += digit

  if is_negative:
    if num > int64.high.uint64 + 1:
      return (translate(31337_33551107641907, "Int literal too big"), 0'u64)

    num = (not num) + 1
  else:
    if num > int64.high.uint64:
      return (translate(31337_33551107641907, "Int literal too big"), 0'u64)

  return ("", num)

func get_line_number*(s: StreamSlice): int =
  var line = 1
  for i in 0 ..< s.source[].len.min(s.start):
    if s.source[i] == '\n':
      line += 1
  return line

func newParseError(s: StreamSlice, msg: string): ref ParseError =
  (ref ParseError)(msg: msg, parent: nil, line: get_line_number(s))

func `?`*[T](input: (string, T)): T =
  if input[0] != "":
    raise newException(ParseError, input[0])
  return input[1]

func `?`*(input: (string, StreamSlice)): StreamSlice =
  if input[0] != "":
    raise newException(
      ParseError,
      translate(
        31337_22378976352410, "Line {num}: ", ("num", get_line_number(input[1]))
      ) & input[0],
    )
  return input[1]

func get_size*(s: var StreamSlice): (string, uint64, bool) =
  let cp = checkpoint(s)

  if peek(s) notin {'U', 'S'}:
    result[0] =
      translate(31337_43326454052643, "Expected an U for unsigned or S for signed here")
    return

  result[2] = read(s) == 'S'

  let s_number = get_unsigned(s).on_err:
    result[0] = err
    return

  change_token_kind(s, tk_number, tk_type_name)

  if s_number.len == 0:
    s.restore(cp)
    result[0] = translate(31337_77089554485217, "Expected a size declaration here")
    return
  add_token(s, tk_type_name)

  let number = parse_unsigned(s_number).on_err:
    result[0] = err
    return

  result[1] = number

iterator items*(s: StreamSlice): char =
  var i = s.start
  while i < s.finish:
    yield s.source[i]
    i += 1

iterator pairs*(s: StreamSlice): (int, char) =
  var i = s.start
  while i < s.finish:
    yield (i - s.start, s.source[i])
    i += 1

func `==`*(a: StreamSlice, b: StreamSlice): bool =
  if a.source == b.source and a.start == b.start and a.finish == b.finish:
    return true
  if a.len != b.len:
    return false
  for i, c in a:
    if b[i] != c:
      return false
  return true

func `==`*(a: StreamSlice, b: string): bool =
  if a.len != b.len:
    return false
  for i, c in a:
    if b[i] != c:
      return false
  return true

func `==`*(a: string, b: StreamSlice): bool =
  return b == a

func `&`*(a: StreamSlice, b: StreamSlice): StreamSlice =
  return new_stream_slice($a & $b)

func `&`*(a: StreamSlice, b: string): StreamSlice =
  return new_stream_slice($a & $b)

func `&`*(a: string, b: StreamSlice): StreamSlice =
  return new_stream_slice($a & $b)

func hash*(s: StreamSlice): Hash =
  # Needed for contexts to be keys in maps
  var h: Hash = 0
  for c in s:
    h = h !& hash(c)
  result = !$h

func get_enum*[T](
    s: var StreamSlice, options: openArray[(string, T)], tk = tk_identifier
): (string, T) =
  for (str, value) in options:
    if s.matches(str, tk = tk):
      return ("", value)

  var joined_options = ""
  for i, (str, _) in options:
    if i != 0: # Not the first element
      joined_options &= ", "
    joined_options &= str
  let current = get_identifier(s, tk = tk)
  if current.len != 0:
    return (
      translate(31337_19807940646400, "Expected one of {expected}, got {actual}")
      .multiReplace(("expected", joined_options), ("actual", $current)),
      default(T),
    )
  else:
    return (
      translate(31337_73113688099439, "Expected one of {expected}").replace(
        "expected", joined_options
      ),
      default(T),
    )

func find*[T: string | char](
    s: var StreamSlice, candidates: openArray[T], tk = tk_none
): int =
  for i, candidate in candidates:
    if matches(s, candidate, tk = tk):
      return i
  return -1

func find*[T: string | char, U](
    s: var StreamSlice, candidates: openArray[(T, U)], tk = tk_none
): Option[U] =
  for candidate in candidates:
    if matches(s, candidate[0], tk = tk):
      return candidate[1].some

func get_bool*(s: var StreamSlice): (string, bool) =
  let index = find(s, ["false", "true"], tk = tk_literal)

  if index == -1:
    return (translate(31337_29112746104375, "Expected a bool here."), false)

  return ("", bool(index))

func get_string*(
    s: var StreamSlice, tk = tk_string, tk_quote = tk
): (string, StreamSlice) =
  let cp = s.checkpoint()

  let quote = s.read(tk = tk_quote)

  if quote notin QUOTES:
    s.restore(cp)
    return (
      translate(31337_27682737127628, "Expected an opening quote (one of \", ' or `)"),
      empty_slice(s),
    )

  while peek(s) != quote:
    if read(s) == '\\':
      discard read(s)
    if finished(s):
      s.restore(cp)
      return (
        translate(31337_75565287060042, "Unexpected EOF while parsing a string"),
        empty_slice(s),
      )

  add_token(s, tk)

  discard read(s, tk = tk_quote)
  result[1] = s
  result[1].start = cp.s.start + 1
  result[1].finish = s.start - 1

func descape_string_content*(s: StreamSlice): (string, string) =
  var it = s
  while not it.finished():
    let c = it.read()
    if c != '\\':
      result[1].add c
      continue
    if it.finished():
      return (translate(31337_10198498286711, "Unfinished escape sequence"), "")
    let nc = it.read()
    case nc
    of 'a':
      result[1].add '\a'
    # Bell (Alert)
    of 'b':
      result[1].add '\b'
    # Backspace
    of 'f':
      result[1].add '\f'
    # Formfeed
    of 'n':
      result[1].add '\n'
    # Linefeed (newline)
    of 'r':
      result[1].add '\r'
    # Carriage Return
    of 't':
      result[1].add '\t'
    # Horizontal Tab
    of 'v':
      result[1].add '\v'
    # Vertical Tab
    of '\\':
      result[1].add '\\'
    of '"':
      result[1].add '"'
    of '\'':
      result[1].add '\''
    of '`':
      result[1].add '`'
    of '0' .. '9':
      var value = nc.ord - '0'.ord
      if peek(it) in DIGITS:
        value = 8 * value + read(it).ord - '0'.ord
      if peek(it) in DIGITS:
        value = 8 * value + read(it).ord - '0'.ord
      if value > 255:
        return (translate(31337_36313699368590, "Invalid octal escape sequence"), "")
      result[1].add char(value)
    of 'x':
      var digit1 = read(it)
      var digit2 = read(it)
      if digit1 not_in HEX_DIGITS or digit2 not_in HEX_DIGITS:
        return (translate(31337_44942745729831, "Invalid hex escape sequence"), "")
      let value = xdigit_to_value(digit1) * 16 + xdigit_to_value(digit2)
      result[1].add char(value)
    else:
      return (
        translate(31337_56457570130031, "Invalid escape character '{nc}'", ("nc", nc)),
        "",
      )

func make_escaped_string*(s: string, quote = '"'): string =
  result &= quote
  for c in s:
    if c in {quote, '\\'}:
      result &= "\\" & c
    if c in {'\x00' .. '\x19'}:
      result &= "\\x" & toHex(c.ord, 2)
    else:
      result &= c
  result &= quote

func parse_string*(s: StreamSlice): (string, string) =
  # To be used with results from get_list_value
  var it = s
  let content = it.get_string().on_err:
    return (err, "")
  return descape_string_content(content)

iterator get_encapsulation*(s: var StreamSlice, tk = tk_bracket): StreamSlice =
  assert not isNil(s.source)

  let cp = s.checkpoint()

  let open = read(s, tk)
  var close: char

  case open
  of '(':
    close = ')'
  of '[':
    close = ']'
  of '{':
    close = '}'
  else:
    s.restore(cp)
      # TODO: Ideally we would not restore here (and in other places where we raise) I think, but that's a behavior change for later
    raise newParseError(
      s,
      translate(
        31337_33400766069212,
        "Expected an opening parantheses (one of '(', '[' or '{{'), got '{open}'",
        ("open", open),
      ),
    )

  skip_newlines(s)
  var inner = s

  var depth = 1
  while true:
    let c = read(s)
    if c == open:
      depth += 1
    elif c == close:
      depth -= 1
      if depth == 0:
        break
    elif c in QUOTES:
      s.start -= 1
      discard get_string(s, tk_none).on_err:
        s.restore(cp)
        raise newParseError(s, err)
    elif finished(s):
      s.restore(cp)
      raise newParseError(
        s,
        translate(
          31337_25983481845150, "Expected '{symbol}', got EOF", ("symbol", close)
        ),
      )

  inner.finish = s.start - 1
  yield inner
  add_token(s, tk)

proc skip_encapsulation*(s: var StreamSlice) =
  for _ in get_encapsulation(s, tk_none):
    discard

func strip*(
    s: StreamSlice
): StreamSlice {.
    deprecated:
      "For better token production, manually use skip_whitespaces/skip_newlines"
.} =
  result = s
  while peek(result) in WHITESPACES + {'\n'}:
    skip(result)
  while result.finish - 1 > 0 and
      result.source[][result.finish - 1] in WHITESPACES + {'\n'}:
    result.finish -= 1

func from_line_start*(s: StreamSlice): StreamSlice =
  result = s
  # Go back one if we are at a newline
  if result.start > 0 and peek(result) == '\n':
    result.start -= 1

  # Seek backwards until the start of the line
  while result.start > 0 and peek(result) != '\n':
    result.start -= 1

  # Go forwards from the start of that line to the end
  result.start += 1
  result.finish = result.start
  while result.finish < s.len and result.source[result.finish] != '\n':
    result.finish += 1

func from_line_start_to_here*(s: StreamSlice): StreamSlice =
  result = s
  result.finish = s.start

  # Go back one if we are at a newline
  if result.start > 0 and peek(result) == '\n':
    result.start -= 1

  # Seek backwards until the start of the line
  while result.start > 0 and peek(result) != '\n':
    result.start -= 1

  if peek(result) == '\n':
    result.start += 1

func get_list_value(s: var StreamSlice): (string, StreamSlice) =
  # This function is not allowed to call add_token with tk!=tk_none
  assert not isNil(s.source)

  let start = s.start

  case peek(s)
  of QUOTES: # These may contain commas
    discard get_string(s, tk = tk_none).on_err:
      return (err, empty_slice(s))
  of '(', '[', '{': # These may contain commas
    skip_encapsulation(s)
  else:
    while peek(s) notin WHITESPACES + {',', ':', '\n', '\0'}:
      skip(s)

  result[1] = s
  result[1].start = start
  result[1].finish = s.start
  result[1] = result[1]

iterator get_list*(s: var StreamSlice): StreamSlice =
  let restore = s
  for raw_inner in get_encapsulation(s):
    var list = raw_inner
    while not finished(list):
      skip_newlines(list)

      let start = list.start
      let element = get_list_value(list).on_err:
        s = restore
        raise newParseError(s, err)
      if list.start == start:
        s = restore
        raise
          newParseError(s, translate(31337_64743950507593, "Expecated a list value"))

      yield element

      skip_newlines(list)

      if peek(list) == ',':
        skip(list, tk = tk_separator)
        skip_newlines(list)

proc get_whole_list*(s: var StreamSlice): seq[StreamSlice] =
  for value in get_list(s):
    result.add(value)

iterator get_table*(s: var StreamSlice): (bool, StreamSlice) =
  # yields (is_value, text). Will always generate a key followed by a value unless an exception is raised

  let restore = s
  for raw_inner in get_encapsulation(s):
    var list = raw_inner
    while not finished(list):
      skip_whitespaces(list)

      let key = get_list_value(list).on_err:
        s = restore
        raise newParseError(s, err)
      if key.len == 0:
        s = restore
        raise newParseError(s, translate(31337_13040813748160, "Expected a key"))
          # Of a table (map) data structure
      yield (false, key)
      skip_whitespaces(list)

      if read(list, tk_separator) != ':':
        s = restore
        raise newParseError(
          s, translate(31337_66187706284192, "Expected ':' after the key")
        ) # Of a table (map) data structure
      skip_whitespaces(list)

      let value = get_list_value(list).on_err:
        s = restore
        raise newParseError(s, err)

      if value.len == 0:
        s = restore
        raise newParseError(s, translate(31337_49180229055343, "Expected a value"))
          # Of a table (map) data structure

      yield (true, value)

      skip_whitespaces(list)
      if peek(list) == ',':
        skip(list, tk = tk_separator)
        skip_newlines(list)
      elif not finished(list):
        s = restore
        raise newParseError(
          s, translate(31337_12492443144951, "Expected a ',' or end of table")
        ) # Of a table (map) data structure

proc get_whole_table*(s: var StreamSlice): OrderedTable[StreamSlice, StreamSlice] =
  var key: StreamSlice

  for is_value, value in get_table(s):
    if not is_value:
      key = value
    else:
      result[key] = value

func parse_parametrized_pattern*(
    s: var StreamSlice, parameters: seq[StreamSlice]
): (seq[string], seq[int]) =
  var slice = s
  slice.finish = slice.start

  while peek(s) notin {'\n', '\0'} or peek(s, 1) notin {'[', '@'}:
    if peek(s) != '`':
      skip(s, tk = tk_text)
      slice.finish = s.start
      continue

    let (err, parameter_name) = get_string(s, tk = tk_pattern_variable)
    if err != "":
      skip(s, tk = tk_text)
      slice.finish = s.start
      continue

    if parameter_name.len <= 0:
      slice.finish = s.start
      continue

    let parameter_index = parameters.find(parameter_name)
    if parameter_index < 0:
      slice.finish = s.start
      change_token_kind(s, tk_pattern_variable, tk_text)
      continue

    result[0].add($slice)
    result[1].add(parameter_index)

    slice.start = s.start
    slice.finish = s.start

  slice.finish += 1
  result[0].add($slice)

  discard read(s, tk = tk_whitespace)

func get_table_value*(s: var StreamSlice): string =
  assert not isNil(s.source)

  skip_whitespaces(s)

  var closing_char: char
  var c = read(s)
  if c in QUOTES:
    closing_char = c
  else:
    raise newParseError(
      s,
      translate(
        31337_11064758781325,
        "Expected '\"', ''', or '`' at the start of UI table cell content",
      ),
    )

  var was_escape = false
  while true:
    c = peek(s)
    if c in {'\r', '\n', '\0'}:
      if was_escape:
        raise newParseError(
          s,
          translate(
            31337_82386938622647,
            "Expected some character after the escape character '\\'",
          ),
        )
      break
    skip(s)

    if was_escape:
      result &= c
      was_escape = false
    elif c == closing_char:
      break
    elif c == '\\':
      was_escape = true
    else:
      result &= c

  skip_whitespaces(s)

iterator get_ui_table*(
    s: var StreamSlice
): tuple[is_row_header: bool, content: string] =
  if read(s, tk_bracket) != ']':
    raise newParseError(
      s, translate(31337_85095060656242, "Expected ']' at the start of the UI table")
    )

  var is_row_header = true

  skip_newlines(s)
  while peek(s) != '[':
    skip_whitespaces(s)
    let (error0, raw_cell) = get_string(s)
    if error0 != "":
      raise newParseError(s, error0)

    let (error1, content) = descape_string_content(raw_cell)
    if error1 != "":
      raise newParseError(s, error1)

    yield (is_row_header, content)
    is_row_header = false

    skip_whitespaces(s)

    let next_char = peek(s)
    if next_char == '\0':
      raise newParseError(
        s, translate(31337_33545106210094, "Expected '[' at the end of the UI table")
      )
    if next_char in {'\n', '\r'}:
      is_row_header = true
      skip_newlines(s)
    elif next_char == ',':
      skip(s, tk = tk_separator)
    else:
      raise newParseError(
        s,
        translate(
          31337_66543091234026,
          "Expected ',' or '\\n' at the end of the UI table cell content",
        ),
      )

  if finished(s):
    raise newParseError(
      s, translate(31337_49158020311750, "Expected '[' at the end of the UI table")
    )

  skip(s, tk = tk_bracket)

iterator get_ui_disassembly_table*(
    s: var StreamSlice
): tuple[is_row_header: bool, is_column_header: bool, content: string] =
  if read(s, tk_bracket) != ']':
    raise newParseError(
      s,
      translate(
        31337_52765180261200, "Expected ']' at the start of the UI disassembly table"
      ),
    )

  var is_column_header = true
  var is_row_header = true

  skip_newlines(s)
  while peek(s) != '[':
    skip_whitespaces(s)
    let (error0, raw_cell) = get_string(s)
    if error0 != "":
      raise newParseError(s, error0)

    let (error1, content) = descape_string_content(raw_cell)
    if error1 != "":
      raise newParseError(s, error1)

    yield (is_row_header, is_column_header, content)
    is_row_header = false

    skip_whitespaces(s)

    let next_char = peek(s)
    if next_char == '\0':
      raise newParseError(
        s,
        translate(
          31337_52918417608842, "Expected '[' at the end of the UI disassembly table"
        ),
      )
    if next_char in {'\n', '\r'}:
      is_row_header = true
      is_column_header = false
      skip_newlines(s)
    elif next_char == ',':
      skip(s, tk = tk_separator)
    else:
      raise newParseError(
        s,
        translate(
          31337_31593726953356,
          "Expected ',' or '\\n' at the end of the UI disassembly table cell content",
        ),
      )

  if finished(s):
    raise newParseError(
      s,
      translate(
        31337_35446186237729, "Expected '[' at the end of the UI disassembly table"
      ),
    )

  skip(s, tk = tk_bracket)
