gs vldmxcsr dword [rax]
gs vldmxcsr dword [r12]
vldmxcsr dword [rbx + 8 * rdx]
vldmxcsr dword [r15d + 2 * edi + 0x72]
gs vldmxcsr dword [esp]
gs a32 vldmxcsr dword [r14d + 1 * edx + 0x7FFFFFFF]
vldmxcsr dword [rax]
vldmxcsr dword [r15 + 2 * rdi + 0x72]
gs vldmxcsr dword [rdx - 0x80000000]
vldmxcsr dword [esp]
gs vldmxcsr dword [r12d]
a32 gs vldmxcsr dword [ebx + 8 * edx]
