vmclear  [rax]
gs vmclear  [rsp + 1 * rbp]
vmclear  [r14 + 1 * rdx + 0x7FFFFFFF]
gs a32 vmclear  [ebp]
a32 gs vmclear  [r14d + 1 * edx + 0x7FFFFFFF]
 gs vmclear  [esp + 1 * ebp]
vmclear  [rbx + 8 * rdx]
 gs vmclear  [rax]
vmclear  [rsp]
gs  vmclear  [r13d]
a32 gs vmclear  [eax]
vmclear  [edx - 0x80000000]
